apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-deployment
  namespace: chatapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-backend
  template:
    metadata:
      labels:
        app: chatapp-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: chatapp-cluster-worker
      containers:
      - name: chatapp-backend
        image: snehalpawar2945/chatapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:secret@mongodb.chatapp-ns.svc.cluster.local:27017/dbname?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
           secretKeyRef:
            name: chatapp-secret
            key: jwt
        - name: "PORT"
          value: "5001"
