apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chatapp-ns
spec:
  type: NodePort
  selector:
    app: chatapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

